---

- name: "Create code dir"
  file:
    path: "/home/{{ ansible_user }}/git"
    state: directory

- name: "Clone Faasm repos"
  git:
    repo: "https://www.github.com/faasm/{{ item }}.git"
    dest: "/home/{{ ansible_user }}/git/faasm/{{ item }}"
    update: yes
    recursive: yes
    clone: yes
    force: yes
    accept_hostkey: yes
  with_items:
    - "examples"
    - "faasm"
    - "rabe"
    - "tless-jwt"
    - "tless"
