---

- name: "Set WASM VM env. variable to SGX"
  shell: "echo 'export FAASM_WASM_VM=sgx' >> /home/{{ ansible_user }}/.bash_aliases"

- name: "Set WASM VM env. variable to SGX"
  shell: "echo 'export PATH=$PATH:/home/{{ ansible_user }}/.local/bin' >> /home/{{ ansible_user }}/.bashrc"

- name: "Update apt cache"
  become: yes
  apt:
    update_cache: yes

- name: "Install linux recommends"
  become: yes
  shell: "apt install --install-recommends -y linux-generic"

- name: "Upgrade to 6.x kernel for EDMM features"
  become: yes
  apt:
    name: linux-image-6.5.0-1025-azure
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: "Reboot to pick-up latest kernel"
  reboot:
  become: yes
