edition = "2024"

# Set the maximum line length
max_width = 100

# Use spaces instead of tabs
hard_tabs = false

# ---- Imports ----

imports_granularity = "Crate"
group_imports = "One"
# group_imports = "StdExternalCrate"

# ---- Formatting ----

# Add a trailing comma on the last item in multi-line lists/structs/enums
# This makes version control diffs much cleaner!
trailing_comma = "Vertical"

# Sort modules alphabetically
reorder_modules = true

# ---- Comments ----

# Format code examples inside your doc comments
format_code_in_doc_comments = true

# Wrap long comments at `max_width`
wrap_comments = true

# Ensure comments start with a space (e.g., `// Foo` not `//Foo`)
normalize_comments = true
