#!/bin/bash

commit_msg_file=$1
commit_msg=`cat $commit_msg_file`
commit_msg_title=$(head -n 1 "$commit_msg_file")
max_length=50

if [ $(echo "$commit_msg_title" | wc -c) -gt $max_length ]; then
    echo "ERROR: Commit message title is too long (maximum $max_length characters)"
    exit 1
fi

if ! echo "$commit_msg" | grep -q -E '\[(accless|accli|applications|as|build|ci|config|docs|scripts|template-graph)\] (B|E|F|W): '; then
	echo "ERROR: Commit message does not match pattern: '[module-name] (B|E|F|W): Short Description"
    echo "ERROR: List of modules: accless, accli, applications, as, build, ci, config, docs, scripts, template-graph"
    exit 1
fi
