- name: "Populate vimrc"
  shell: printf "set tabstop=4\nset softtabstop=4\nset expandtab\nset shiftwidth=4\nset colorcolumn=80\nset splitright\nset splitbelow\nset autoindent\nset cindent\nset relativenumber\nsyntax on" > /home/{{ ansible_user }}/.vimrc
  args:
    executable: /bin/bash
