# -----
# This YAML describes the FINRA workflow for TLess in Knative.
#
# See here for more details on the workflow:
# https://github.com/faasm/accless/blob/main/workflows/finra/README.md
# -----
apiVersion: messaging.knative.dev/v1
kind: Channel
metadata:
  name: ingress-to-fetch-public
  namespace: accless
spec:
  channelTemplate:
    apiVersion: messaging.knative.dev/v1
    kind: InMemoryChannel
---
apiVersion: messaging.knative.dev/v1
kind: Channel
metadata:
  name: ingress-to-fetch-private
  namespace: accless
spec:
  channelTemplate:
    apiVersion: messaging.knative.dev/v1
    kind: InMemoryChannel
---
apiVersion: messaging.knative.dev/v1
kind: Channel
metadata:
  name: fetch-to-audit
  namespace: accless
spec:
  channelTemplate:
    apiVersion: messaging.knative.dev/v1
    kind: InMemoryChannel
---
apiVersion: messaging.knative.dev/v1
kind: Channel
metadata:
  name: audit-to-merge
  namespace: accless
spec:
  channelTemplate:
    apiVersion: messaging.knative.dev/v1
    kind: InMemoryChannel
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: finra-fetch-public
  namespace: accless
spec:
  template:
    spec:
      runtimeClassName: ${RUNTIME_CLASS_NAME}
      containers:
        - image: sc2cr.io/accless-knative-worker:${ACCLESS_VERSION}
          ports:
            - containerPort: 8080
          workingDir: /workflows/finra/knative
          command: [ "./target/release/accless-cloudevent-handler" ]
          env:
            - name: ACCLESS_MODE
              value: "${ACCLESS_MODE}"
    metadata:
      labels:
        accless.workflows/name: finra-fetch-public
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: finra-fetch-private
  namespace: accless
spec:
  template:
    spec:
      runtimeClassName: ${RUNTIME_CLASS_NAME}
      containers:
        - image: sc2cr.io/accless-knative-worker:${ACCLESS_VERSION}
          ports:
            - containerPort: 8080
          workingDir: /workflows/finra/knative
          command: [ "./target/release/accless-cloudevent-handler" ]
          env:
            - name: ACCLESS_MODE
              value: "${ACCLESS_MODE}"
    metadata:
      labels:
        accless.workflows/name: finra-fetch-private
---
apiVersion: sinks.knative.dev/v1alpha1
kind: JobSink
metadata:
  name: finra-audit
  namespace: accless
spec:
  job:
    spec:
      completions: 1
      parallelism: 1
      backoffLimit: 4
      # Clean-up jobs once they are finished
      ttlSecondsAfterFinished: 30
      template:
        spec:
          runtimeClassName: ${RUNTIME_CLASS_NAME}
          restartPolicy: OnFailure
          containers:
            - name: main
              image: sc2cr.io/accless-knative-worker:${ACCLESS_VERSION}
              ports:
                - containerPort: 8080
              workingDir: /workflows/finra/knative
              command: [ "./target/release/accless-cloudevent-handler" ]
              env:
                - name: CE_FROM_FILE
                  value: "on"
                - name: ACCLESS_MODE
                  value: "${ACCLESS_MODE}"
        metadata:
          labels:
            accless.workflows/name: finra-audit
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: finra-merge
  namespace: accless
spec:
  template:
    spec:
      runtimeClassName: ${RUNTIME_CLASS_NAME}
      containers:
        - image: sc2cr.io/accless-knative-worker:${ACCLESS_VERSION}
          ports:
            - containerPort: 8080
          workingDir: /workflows/finra/knative
          command: [ "./target/release/accless-cloudevent-handler" ]
          env:
            - name: ACCLESS_MODE
              value: "${ACCLESS_MODE}"
    metadata:
      labels:
        accless.workflows/name: finra-merge
      annotations:
        # High grace-period to guarantee the same instance processes requests
        # for all jobs in the JobSink (i.e. instances of the audit function)
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: "1m"
---
apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: edge-one-subscription
  namespace: accless
spec:
  channel:
    apiVersion: messaging.knative.dev/v1
    kind: Channel
    name: ingress-to-fetch-public
  reply:
    ref:
      apiVersion: messaging.knative.dev/v1
      kind: InMemoryChannel
      name: fetch-to-audit
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: finra-fetch-public
---
apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: edge-two-subscription
  namespace: accless
spec:
  channel:
    apiVersion: messaging.knative.dev/v1
    kind: Channel
    name: ingress-to-fetch-private
  reply:
    ref:
      apiVersion: messaging.knative.dev/v1
      kind: InMemoryChannel
      name: fetch-to-audit
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: finra-fetch-private
---
apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: edge-three-subscription
  namespace: accless
spec:
  channel:
    apiVersion: messaging.knative.dev/v1
    kind: Channel
    name: fetch-to-audit
  subscriber:
    ref:
      apiVersion: sinks.knative.dev/v1alpha1
      kind: JobSink
      name: finra-audit
---
apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: edge-four-subscription
  namespace: accless
spec:
  channel:
    apiVersion: messaging.knative.dev/v1
    kind: Channel
    name: audit-to-merge
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: finra-merge
---
