# -----
# This YAML describes the common k8s resources be used by all workflows in
# TLess.
# -----
apiVersion: v1
kind: Namespace
metadata:
  name: accless
---
# All workflows share a common storage backend with MinIO
apiVersion: v1
kind: Pod
metadata:
  name: minio
  namespace: accless
  labels:
    accless.workflows/name: minio
spec:
  containers:
    - name: minio-main
      image: minio/minio:RELEASE.2024-09-13T20-26-02Z
      args: ["server", "/data/minio"]
      env:
        - name: MINIO_ROOT_USER
          value: "minio"
        - name: MINIO_ROOT_PASSWORD
          value: "minio123"
      ports:
        - containerPort: 9000
      volumeMounts:
        - mountPath: /data/minio
          name: minio-volume
  volumes:
    - name: minio-volume
      emptyDir: {}
---
# Allow minio to be accessed by other pods
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: accless
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
  selector:
    accless.workflows/name: minio
