- name: "Install APT depdencencies"
  become: yes
  apt:
    name:
      - build-essential
      - cmake
      - libboost-all-dev
      - libcurl4-openssl-dev
      - libjsoncpp-dev
      - libssl-dev
      - nlohmann-json3-dev
    update_cache: yes
