---

- name: "Create code dir"
  file:
    path: "/home/{{ ansible_user }}/git"
    state: directory

- name: "Clone TLess repos"
  git:
    repo: "https://www.github.com/faasm/{{ item }}.git"
    dest: "/home/{{ ansible_user }}/git/faasm/{{ item }}"
    update: yes
    recursive: no
    clone: yes
    force: yes
    accept_hostkey: yes
  with_items:
    - "tless"

- name: "Clone Azure repos"
  git:
    repo: "https://www.github.com/Azure/{{ item }}.git"
    dest: "/home/{{ ansible_user }}/git/azure/{{ item }}"
    update: yes
    recursive: no
    clone: yes
    force: yes
    accept_hostkey: yes
  with_items:
    - "confidential-computing-cvm-guest-attestation"
