use crate::{
    intel::{INTEL_PCS_URL, IntelCa, SgxCollateral, SgxQuote},
    jwt::JwtClaims,
    request::{NodeData, Tee},
    state::AttestationServiceState,
};
use aes_gcm::{
    Aes128Gcm, KeyInit, Nonce,
    aead::{Aead, OsRng, rand_core::RngCore},
};
use anyhow::{Result, anyhow};
use axum::{Extension, Json, http::StatusCode, response::IntoResponse};
use base64::{Engine as _, engine::general_purpose};
use log::{debug, error, info};
use p256::PublicKey;
use ring::{
    agreement::{self, ECDH_P256, UnparsedPublicKey},
    rand::SystemRandom,
};
use serde::Deserialize;
use serde_json::json;
use std::{
    str::FromStr,
    sync::Arc,
    time::{SystemTime, UNIX_EPOCH},
};

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct InitTimeData {
    _data: String,
    _data_type: String,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct RuntimeData {
    data: String,
    _data_type: String,
}

const MOCK_QUOTE_MAGIC: &[u8; 8] = b"ACCLSGX!";
const MOCK_QUOTE_VERSION: u32 = 1;
const MOCK_QUOTE_HEADER_LEN: usize = 16;

struct MockSgxQuote {
    report_data: [u8; 64],
}

impl MockSgxQuote {
    fn parse(bytes: &[u8]) -> Result<Self> {
        if bytes.len() != MOCK_QUOTE_HEADER_LEN + 64 {
            return Err(anyhow!(
                "mock SGX quote must be {} bytes (got={})",
                MOCK_QUOTE_HEADER_LEN + 64,
                bytes.len()
            ));
        }

        if bytes[..MOCK_QUOTE_MAGIC.len()] != *MOCK_QUOTE_MAGIC {
            return Err(anyhow!("invalid mock SGX quote header"));
        }

        let version_bytes: [u8; 4] = bytes[MOCK_QUOTE_MAGIC.len()..MOCK_QUOTE_MAGIC.len() + 4]
            .try_into()
            .expect("slice size already checked");
        let version = u32::from_le_bytes(version_bytes);
        if version != MOCK_QUOTE_VERSION {
            return Err(anyhow!(
                "unsupported mock SGX quote version (expected={}, got={})",
                MOCK_QUOTE_VERSION,
                version
            ));
        }

        let mut report_data = [0u8; 64];
        report_data.copy_from_slice(&bytes[MOCK_QUOTE_HEADER_LEN..]);

        Ok(Self { report_data })
    }
}

/// # Description
///
/// This struct corresponds to the request that SGX-Faasm sends to verify an SGX
/// report. Some of the fields are legacy from when we used Azure's Attestation
/// Service, and they are now unused. The implementation of the client-side
/// protocol is upstreamed in Faasm, because it relies on coordination from
/// inside/outside the Faaslet (i.e. WASM module) and inside/outside the SGX
/// enclave. We provide a mock implementation of the SGX client with Accless'
/// attestation library for testing purposes.
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SgxRequest {
    _draft_policy_for_attestation: String,
    /// Attributes used for CP-ABE keygen.
    node_data: NodeData,
    _init_time_data: InitTimeData,
    /// Base64-encoded SGX quote as generated by the Quoting Enclave.
    quote: String,
    /// Additional base64-encoded data that we send with the enclave as part of
    /// the enclave held data. Even if slightly redundant, it is easier to
    /// access as a standalone field, and we check its integrity from the
    /// quote itself, which is signed by the QE.
    runtime_data: RuntimeData,
}

fn is_valid_p256_point(bytes: &[u8]) -> bool {
    if bytes.len() != 65 || bytes[0] != 0x04 {
        return false;
    }
    PublicKey::from_sec1_bytes(bytes).is_ok()
}

/// # Description
///
/// SGX's crypto library uses little-endian encoding for the coordinates in
/// the crypto library, whereas Rust's ring uses big-endian. We thus need to
/// convert the raw bytes we receive, as part of the enclave's held data in
/// the report, to big endian
fn sgx_pubkey_to_sec1_format(raw: &[u8]) -> Option<[u8; 65]> {
    if raw.len() != 64 {
        return None;
    }

    let mut sec1 = [0u8; 65];
    sec1[0] = 0x04;

    // Reverse gx (first 32 bytes)
    for i in 0..32 {
        sec1[1 + i] = raw[31 - i];
    }

    // Reverse gy (next 32 bytes)
    for i in 0..32 {
        sec1[33 + i] = raw[63 - i];
    }

    Some(sec1)
}

/// # Description
///
/// Reverse the process above: given a SEC1 key usable in Rust, convert it
/// to something we can parse in the SGX SDK
fn sec1_pubkey_to_sgx(sec1_pubkey: &[u8]) -> anyhow::Result<Vec<u8>> {
    // Skip prefix indicatting raw (uncompressed) point
    let gx_be = &sec1_pubkey[1..33];
    let gy_be = &sec1_pubkey[33..65];

    // Big-endian → Little-endian
    let mut gx_le = gx_be.to_vec();
    let mut gy_le = gy_be.to_vec();
    gx_le.reverse();
    gy_le.reverse();

    let mut sgx_le_pubkey = Vec::with_capacity(64);
    sgx_le_pubkey.extend_from_slice(&gx_le);
    sgx_le_pubkey.extend_from_slice(&gy_le);

    Ok(sgx_le_pubkey)
}

/// # Description
///
/// Helper method to fetch the SGX quote collateral. This is the information we
/// need to validate that the quote is correct. We need to fetch it once per
/// TCB, but then we can cache it for subsequent requests.
///
/// In Azure, in general, we can use a Provisioning Certificate Caching Service
/// (PCCS) that prevents having to send a request to Intel for the collateral.
///
/// # Arguments
///
/// - `cache_key`: key in the SGX collateral cache that indicates the TCB of the
///   quote we are trying to validate. It comes from the SGX quote itself.
/// - `state`: handle to the state that contains the SGX quote cache.
///
/// # Returns
///
/// The SGX collateral, either read from the cache, or fetched from Intel's PCS
/// or a cloud-based PCCS.
async fn get_sgx_collateral(
    cache_key: (String, IntelCa),
    state: &Arc<AttestationServiceState>,
) -> Result<SgxCollateral> {
    // Fast path: read collateral from the cache.
    let maybe_collateral: Option<SgxCollateral> = {
        let cache = state.sgx_collateral_cache.read().await;
        cache.get(&cache_key).cloned()
    };

    if let Some(collateral) = maybe_collateral {
        return Ok(collateral);
    };

    // Slow path: fetch collateral from either Intel's PCS or a cloud's PCCS.
    let pccs_url: Option<&str> = state.sgx_pccs_url.as_deref().and_then(|path| path.to_str());

    let collateral: SgxCollateral = if let Some(pccs_url) = pccs_url {
        debug!("fetching SGX collateral from PCCS (url={pccs_url})");
        dcap_qvl::collateral::get_collateral_for_fmspc(
            pccs_url,
            cache_key.0.clone(),
            cache_key.1.as_str(),
            true,
        )
        .await
        .map_err(|e| {
            anyhow::anyhow!("Error fetching SGX collateral from PCCS (url={pccs_url}, error={e:?})")
        })?
    } else {
        debug!("fetching SGX collateral from Intel's PCS (url={INTEL_PCS_URL})");
        dcap_qvl::collateral::get_collateral_for_fmspc(
            INTEL_PCS_URL,
            cache_key.0.clone(),
            cache_key.1.as_str(),
            true,
        )
        .await
        .map_err(|e| {
            anyhow::anyhow!("Error fetching SGX collateral from Intel's PCS (error={e:?})")
        })?
    };

    // Cache collateral for future use.
    {
        let mut cache = state.sgx_collateral_cache.write().await;
        cache.insert(cache_key, collateral.clone());
    }

    Ok(collateral)
}

/// # Description
///
/// Entrypoint function to verify an SGX report.
pub async fn verify_sgx_report(
    Extension(state): Extension<Arc<AttestationServiceState>>,
    Json(payload): Json<SgxRequest>,
) -> impl IntoResponse {
    // Decode the quote
    // WARNING: we must use URL_SAFE as on the client side we are encoding
    // with cppcodec::base64_url
    let raw_quote_b64 = payload.quote.replace(['\n', '\r'], "");
    let quote_bytes = match general_purpose::URL_SAFE.decode(&raw_quote_b64) {
        Ok(bytes) => bytes,
        Err(e) => {
            error!("invalid base64 string in SGX quote (error={e:?})");
            return (
                StatusCode::BAD_REQUEST,
                Json(json!({ "error": "invalid base64 in quote" })),
            );
        }
    };

    let report_data_bytes: Vec<u8> = if state.mock_sgx {
        match MockSgxQuote::parse(&quote_bytes) {
            Ok(mock_quote) => {
                info!("received mock SGX quote, skipping DCAP verification");
                mock_quote.report_data.to_vec()
            }
            Err(e) => {
                error!("invalid mock SGX quote (error={e:?})");
                return (
                    StatusCode::BAD_REQUEST,
                    Json(json!({ "error": "invalid mock SGX quote" })),
                );
            }
        }
    } else {
        // Parse the bytes into an SgxQuote structure.
        let sgx_quote: SgxQuote = match SgxQuote::parse(&quote_bytes) {
            Ok(sgx_quote) => sgx_quote,
            Err(e) => {
                error!("error parsing SGX quote (error={e:?})");
                return (
                    StatusCode::INTERNAL_SERVER_ERROR,
                    Json(json!({ "error": "error parsing SGX quote" })),
                );
            }
        };

        // Extract the key we use in the collateral cache.
        let sgx_tcb_key: (String, IntelCa) = match (sgx_quote.fmspc(), sgx_quote.ca()) {
            (Ok(sgx_fmpsc), Ok(sgx_ca)) => match IntelCa::from_str(sgx_ca) {
                Ok(parsed_ca) => (hex::encode_upper(sgx_fmpsc), parsed_ca),
                Err(_) => {
                    error!("invalid CA returned by SGX quote: {sgx_ca}");
                    return (
                        StatusCode::INTERNAL_SERVER_ERROR,
                        Json(json!({ "error": "invalid CA in SGX quote" })),
                    );
                }
            },
            _ => {
                error!("error extracting FMSPC and CA from SGX quote");
                return (
                    StatusCode::INTERNAL_SERVER_ERROR,
                    Json(json!({ "error": "error extracting CA and FMSPC from SGX quote" })),
                );
            }
        };

        // Fetch the collateral to validate the quote.
        let collateral: SgxCollateral = match get_sgx_collateral(sgx_tcb_key, &state).await {
            Ok(collateral) => collateral,
            Err(e) => {
                error!("error fetching SGX collateral (error={e:?})");
                return (
                    StatusCode::INTERNAL_SERVER_ERROR,
                    Json(json!({ "error": "error fetching SGX collateral" })),
                );
            }
        };

        let now = match SystemTime::now().duration_since(UNIX_EPOCH) {
            Ok(t) => t.as_secs(),
            Err(e) => {
                error!("error getting time since epoch (error={e:?})");
                return (
                    StatusCode::INTERNAL_SERVER_ERROR,
                    Json(json!({ "error": "error getting time since epoch" })),
                );
            }
        };
        let verified_report = match dcap_qvl::verify::verify(&quote_bytes, &collateral, now) {
            Ok(tcb) => tcb,
            Err(e) => {
                error!("failed to verify SGX's quote (error={e:?})");
                return (
                    StatusCode::INTERNAL_SERVER_ERROR,
                    Json(json!({ "error": "failed to verify SGX quote" })),
                );
            }
        };

        info!("verififed sgx report (status={})", verified_report.status);

        match verified_report.report {
            dcap_qvl::quote::Report::SgxEnclave(enclave_report) => {
                enclave_report.report_data.to_vec()
            }
            _ => {
                error!("received TDX report instead of SGX one");
                return (
                    StatusCode::INTERNAL_SERVER_ERROR,
                    Json(json!({ "error": "received TDX report instead of SGX one" })),
                );
            }
        }
    };

    // Use the enclave held data (runtime_data) public key, to derive an
    // encryption key to protect the returned JWT, which contains secrets.
    debug!("decoding base64 encoded public key in quote.runtime_data");
    let raw_pubkey_bytes = match general_purpose::URL_SAFE.decode(&payload.runtime_data.data) {
        Ok(b) => b,
        Err(_) => {
            return (
                StatusCode::BAD_REQUEST,
                Json(json!({ "error": "invalid base64 in runtimeData.data" })),
            );
        }
    };

    // Verify that the raw-bytes included in the runtime data match the enclave held
    // data in the verified report.
    if raw_pubkey_bytes != report_data_bytes {
        error!(
            "enclave held data does not match verified report data (expected={raw_pubkey_bytes:?}, got={:?})",
            report_data_bytes
        );
        return (
            StatusCode::BAD_REQUEST,
            Json(json!({ "error": "enclave held data does not match verified report data" })),
        );
    }

    debug!("parsing pub key bytes to SEC1 format");
    let pubkey_bytes = match sgx_pubkey_to_sec1_format(&raw_pubkey_bytes) {
        Some(b) => b,
        None => {
            error!("error converting SGX public key to SEC1 format");
            return (
                StatusCode::BAD_REQUEST,
                Json(json!({ "error": "invalid public key length" })),
            );
        }
    };
    if !is_valid_p256_point(&pubkey_bytes) {
        error!("error validating SGX-provided public key");
        return (
            StatusCode::BAD_REQUEST,
            Json(json!({ "error": "invalid EC public key" })),
        );
    }

    // Parse EC P-256 public key
    let peer_pubkey = UnparsedPublicKey::new(&ECDH_P256, pubkey_bytes);

    // Generate ephemeral private key and do ECDH
    debug!("generating server-side ephemeral private key for ECDH key exchange");
    let rng = SystemRandom::new();
    let my_private_key = match agreement::EphemeralPrivateKey::generate(&ECDH_P256, &rng) {
        Ok(k) => k,
        Err(e) => {
            error!("error generating ECDH private key (error={e:?})");
            return (
                StatusCode::INTERNAL_SERVER_ERROR,
                Json(json!({ "error": "key generation failed" })),
            );
        }
    };

    // Also prepare the public part of the ephemeral key we have used for the
    // key derivation step above
    // WARNING: when encoding in base64, the decoder will run inside an SGX
    // enclave, and our home-baked base64 decoding assumes STANDARD (not
    // URL_SAFE) encoding
    debug!("generating server-side ephemeral public key for ECDH key exchange");
    let server_pub_key = my_private_key.compute_public_key().unwrap();
    let server_pub_key_le = sec1_pubkey_to_sgx(server_pub_key.as_ref()).unwrap();
    let server_pub_b64 = general_purpose::STANDARD.encode(server_pub_key_le);

    // Now do the key derivation
    debug!("running server-side key derivation for ECDH key exchange");
    let shared_secret: Vec<u8> =
        match agreement::agree_ephemeral(my_private_key, &peer_pubkey, |shared_secret_material| {
            Ok::<Vec<u8>, ring::error::Unspecified>(shared_secret_material.to_vec())
        }) {
            Ok(secret) => secret.unwrap(),
            Err(_) => {
                return (
                    StatusCode::INTERNAL_SERVER_ERROR,
                    Json(json!({ "error": "EC key agreement failed" })),
                );
            }
        };

    // WARNING: the SGX-SDK only implements AES 128, so we must use it here
    // instead of AES 256
    debug!("generating AES-128-GCM key from ECDH secret");
    let cipher = match Aes128Gcm::new_from_slice(&shared_secret[..16]) {
        Ok(cipher) => cipher,
        Err(e) => {
            error!("error initializing AES 128 GCM cipher: {:?}", e);
            return (
                StatusCode::INTERNAL_SERVER_ERROR,
                Json(json!({ "error": "JWT encoding failed" })),
            );
        }
    };

    debug!("encoding JWT with server's private key (for authenticity)");
    let claims = match JwtClaims::new(
        &state,
        &Tee::Sgx,
        &payload.node_data.gid,
        &payload.node_data.workflow_id,
        &payload.node_data.node_id,
    ) {
        Ok(claims) => claims,
        Err(e) => {
            error!("error gathering JWT claims (error={e:?})");
            return (
                StatusCode::INTERNAL_SERVER_ERROR,
                Json(json!({ "error": "JWT claims gathering" })),
            );
        }
    };
    let header = jsonwebtoken::Header {
        alg: jsonwebtoken::Algorithm::RS256,
        ..Default::default()
    };
    let jwt = match jsonwebtoken::encode(&header, &claims, &state.jwt_encoding_key) {
        Ok(t) => t,
        Err(e) => {
            error!("JWT encode error (error={e:?})");
            return (
                StatusCode::INTERNAL_SERVER_ERROR,
                Json(json!({ "error": "JWT encoding failed" })),
            );
        }
    };

    // Encrypt the JWT
    debug!("encrypting JWT with ECDH-derived AES key (for confidentiality)");
    let mut nonce_bytes = [0u8; 12];
    OsRng.fill_bytes(&mut nonce_bytes);
    let nonce = Nonce::from(nonce_bytes);

    let ciphertext = match cipher.encrypt(&nonce, jwt.as_bytes()) {
        Ok(ct) => ct,
        Err(e) => {
            error!("error encrypting JWT (error={e:?})");
            return (
                StatusCode::INTERNAL_SERVER_ERROR,
                Json(json!({ "error": "JWT encryption failed" })),
            );
        }
    };

    // Return base64(nonce + ciphertext) as a JSON payload
    let mut combined = nonce_bytes.to_vec();
    combined.extend_from_slice(&ciphertext);

    let encrypted_b64 = general_purpose::STANDARD.encode(&combined);
    let response = json!({
        "encrypted_token": encrypted_b64,
        "server_pubkey": server_pub_b64
    });

    (StatusCode::OK, Json(response))
}
