- name: "Build demo"
  shell: mkdir build && cd build && cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release && ninja
  args:
    chdir: "/home/{{ ansible_user }}/git/faasm/tless/ubench/escrow-xput"
    executable: /bin/bash

- name: "Generate keys"
  shell: ./bin/gen_keys.sh
  args:
    chdir: "/home/{{ ansible_user }}/git/faasm/tless/attestation-service"
    executable: /bin/bash
  environment:
    AS_URL: "{{ as_ip }}"

- name: "Build Attestation Service"
  shell: cargo build --release
  args:
    chdir: "/home/{{ ansible_user }}/git/faasm/tless/attestation-service"
    executable: /bin/bash
  environment:
    PATH: "/home/{{ ansible_user }}/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
