---

- name: "Deploy SC2 cluster"
  shell: rm -rf ./venv && source ./bin/workon.sh && inv sc2.deploy --clean
  args:
    chdir: "/home/{{ ansible_user }}/git/sc2-sys/deploy"
    executable: /bin/bash
  environment:
    PATH: "/home/{{ ansible_user }}/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# TODO: build workflows here, and patch with the right certificate for the AS
# we just need to pack the container image, so we can do it locally?
