- name: "Build KBS"
  shell: make cli CLI_FEATURES=sample_only,az-snp-vtpm-attester
  args:
    chdir: "/home/{{ ansible_user }}/git/confidential-containers/trustee/kbs"
    executable: /bin/bash
  environment:
    PATH: "/home/{{ ansible_user }}/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

- name: "Build KBS CLI"
  shell: make background-check-kbs
  args:
    chdir: "/home/{{ ansible_user }}/git/confidential-containers/trustee/kbs"
    executable: /bin/bash
  environment:
    PATH: "/home/{{ ansible_user }}/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

- name: "Prepare certs and keys for KBS load test"
  shell: make kbs-certs /home/{{ ansible_user }}/git/confidential-containers/trustee/kbs/test/work/tee.key /home/{{ ansible_user }}/git/confidential-containers/trustee/kbs/test/work/repository/one/two/three
  args:
    chdir: "/home/{{ ansible_user }}/git/confidential-containers/trustee/kbs/test"
    executable: /bin/bash
  environment:
    PATH: "/home/{{ ansible_user }}/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
