---

- name: "Add Docker GPG key"
  become: yes
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: "Add Docker APT repository"
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"

- name: "Install Docker"
  become: yes
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    update_cache: yes

- name: "Add user to docker group"
  become: yes
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
