- name: "Populate vimrc"
  shell: echo "set tabstop=4
        set softtabstop=4
        set expandtab
        set shiftwidth=4
        set colorcolumn=80
        set splitright
        set splitbelow
        set autoindent
        set cindent
        set relativenumber
        syntax on" > /home/{{ ansible_user }}/.vimrc
  args:
    executable: /bin/bash
