[package]
name = "load-test"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "^1.0"
chrono = { version = "^0.4", features = ["serde"] }
csv = "^1.3"
futures = "^0.3"
tokio = { version = "^1.37", features = ["full"] }
serde = { version = "^1.0", features = ["derive"] }
