---

- hosts: snpknative
  gather_facts: yes
  tasks:
    - include_tasks: tasks/snp-knative/apt.yaml
    # Install docker before updating the host kernel so that the reboot in the
    # latter also means we can use docker without sudo (which also requires a
    # reboot)
    - include_tasks: tasks/util/docker.yaml
    - include_tasks: tasks/snp-knative/update_host_kernel.yaml
    - include_tasks: tasks/snp-knative/qemu.yaml
    - include_tasks: tasks/util/rust.yaml
    - include_tasks: tasks/snp-knative/code.yaml
      # - include_tasks: tasks/snpknative.yml
