name: "Formatting checks"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]

defaults:
  run:
    shell: bash

# Cancel previous running actions for the same PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  checks:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-24.04
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
      - name: "Install clang-format"
        run: sudo apt install -y clang-format
      - name: "Run formatting checks"
        run: ./bin/invrs_wrapper.sh format-code --check
