name: "Integration Tests"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]

defaults:
  run:
    shell: bash

# Cancel previous running actions for the same PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  checks:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-24.04
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
      - name: "Install clang-format"
        run: sudo apt install -y clang-format
      - name: "Run formatting checks"
        run: ./scripts/accli_wrapper.sh dev format-code

  rust-unit-tests:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-24.04
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
      - name: "Run Rust unit tests"
        run: |
          source ./scripts/workon.sh
          cargo test

  cpp-unit-tests:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-24.04
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
      - name: "Build C++ code"
        shell: bash
        run: |
          ./scripts/accli_wrapper.sh docker run --mount --cwd /code/accless/accless python3 build.py
      - name: "Run C++ unit tests"
        shell: bash
        run: |
          ./scripts/accli_wrapper.sh docker run --mount --cwd /code/accless/accless/build-native  ctest -- --output-on-failure
