---

- name: "Install APT depdencencies"
  become: yes
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - libssl-dev
      - pkg-config
      - software-properties-common
      - python3.10-dev
      - python3-pip
      - python3.10-venv
      - unzip
    update_cache: yes
