---

- name: "Download the kernel with Azure's patches"
  get_url:
    url: "https://github.com/jepio/AMDSEV/releases/download/v2024.02.24/linux-image-6.8.0-rc5-next-20240221-snp-host-2cfe07293708_6.8.0-rc5-g2cfe07293708-2_amd64.deb"
    dest: "/tmp/linux-image.deb"
    mode: '0644'

- name: "Install the new kernel package"
  become: true
  apt:
    deb: "/tmp/linux-image.deb"
    state: present

- name: "Update GRUB to pick up the newly installed kernel"
  become: true
  command: update-grub

- name: "List all installed kernels"
  shell: dpkg --list | grep linux-image
  register: installed_kernels

# You can see the different options by running `dpkg --list | grep linux-image`
- name: "Set the default kernel in GRUB"
  become: true
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_DEFAULT='
    line: 'GRUB_DEFAULT="Advanced options for Ubuntu>Ubuntu, with Linux 6.8.0-rc5-next-20240221-snp-host-2cfe07293708"'

- name: "Update GRUB configuration again to pick up new changes"
  become: true
  command: update-grub
  when: installed_kernels is changed

- name: "Reboot the system to apply the new kernel"
  become: true
  reboot:
    reboot_timeout: 600
    test_command: uname -r
  register: reboot_result
